name: Continuous Build and Test

on:
  push:
    branches:
      - 'develop'
    paths-ignore:
      # don't need to re-run the build for now if only markdown changes
      - '**/*.md'
      - 'docs/**'
  pull_request:
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

defaults:
  run:
    shell: bash

jobs:


  export:
    strategy:
      fail-fast: false
      matrix:
        configuration: [ "--export-debug", "--export-release" ]
        platform: [ { preset: "linux_amd64", bin: "export/YarnSpinnerGodot_Samples.x86_64" },
                    { preset: "win64", bin: "export/YarnSpinnerGodot_Samples.exe" } ]
    
    
    name: Export ${{ matrix.configuration }}  ${{ matrix.platform.preset }}
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          clean: false # we clean what we want to clean ourselves above, and try to keep some cache
          submodules: recursive

      - uses: chickensoft-games/setup-godot@v1
        name: 🤖 Setup Godot
        with:
          version: 4.6.2
          # Use .NET-enabled version of Godot (the default is also true).
          use-dotnet: true
          include-templates: true
          
      - name: 🔬 Verify Setup
        run: |
          dotnet --version
          godot --version

      - name: Build solution & Import
        id: buildSolution
        run: |
          godot --import --headless
          godot --headless --path . --verbose -e --build-solutions --quit 
          godot --headless --path . --verbose -e --import --quit 
        timeout-minutes: 3

      - name: Export
        run: |
          mkdir export
          godot --headless --verbose ${{ matrix.configuration }}  ${{ matrix.platform.preset }}  ${{ matrix.platform.bin }}
          